### ISSUE TITLE
Websocket error: org.slf4j.helpers.MessageFormatter.arrayFormat

### ISSUE THREAD

**Issue by spapapan** [webcerebrium/java-binance-api#16]
I am trying to run:

```
BinanceSymbol symbol = new BinanceSymbol("ETHBTC");
Session session = (new BinanceApi()).websocketDepth(symbol, new BinanceWebSocketAdapterDepth() {
    @Override
    public void onMessage(BinanceEventDepthUpdate message) {
        System.out.println(message.toString());
    }
});
try { Thread.sleep(5000); } catch (InterruptedException e) {}
session.close();
```

But I get this error:

> 
> com.webcerebrium.binance.api.BinanceApiException: Websocket error: org.slf4j.helpers.MessageFormatter.arrayFormat(Ljava/lang/String;[Ljava/lang/Object;)Lorg/slf4j/helpers/FormattingTuple;
> 	at com.webcerebrium.binance.api.BinanceApi.getWebsocketSession(BinanceApi.java:631)
> 	at com.webcerebrium.binance.api.BinanceApi.websocketDepth(BinanceApi.java:643)

I guess there is something wrong with the dependencies.

<img src="https://i.imgur.com/imfU63g.png">

Any ideas ?

**Comment by wcrbrm** [comment]
may be slf4j-api instead of slf4j?

**Comment by spapapan** [comment]
I used slf4j-api and logback lastest version. The error is gone, the program is running but I don't see any output.

**Comment by wcrbrm** [comment]
well. We truly don't think you should not me managing dependencies manually

Here is the full list of actual dependencies that are now resolved by gradle (from IML file)
```
    <orderEntry type="library" name="Gradle: org.json:json:20160810" level="project" />
    <orderEntry type="library" name="Gradle: com.google.code.gson:gson:2.7" level="project" />
    <orderEntry type="library" name="Gradle: ch.qos.logback:logback-classic:1.2.2" level="project" />
    <orderEntry type="library" name="Gradle: commons-net:commons-net:3.3" level="project" />
    <orderEntry type="library" name="Gradle: commons-io:commons-io:2.4" level="project" />
    <orderEntry type="library" name="Gradle: commons-collections:commons-collections:3.2.2" level="project" />
    <orderEntry type="library" name="Gradle: com.google.guava:guava:19.0" level="project" />
    <orderEntry type="library" name="Gradle: org.projectlombok:lombok:1.16.4" level="project" />
    <orderEntry type="library" name="Gradle: ch.qos.logback:logback-core:1.2.2" level="project" />
    <orderEntry type="library" name="Gradle: org.slf4j:slf4j-api:1.7.25" level="project" />
    <orderEntry type="library" name="Gradle: commons-codec:commons-codec:1.9" level="project" />
    <orderEntry type="library" name="Gradle: org.eclipse.jetty.websocket:websocket-client:9.4.7.v20170914" level="project" />
    <orderEntry type="library" name="Gradle: org.eclipse.jetty:jetty-client:9.4.7.v20170914" level="project" />
    <orderEntry type="library" name="Gradle: org.eclipse.jetty:jetty-xml:9.4.7.v20170914" level="project" />
    <orderEntry type="library" name="Gradle: org.eclipse.jetty:jetty-util:9.4.7.v20170914" level="project" />
    <orderEntry type="library" name="Gradle: org.eclipse.jetty:jetty-io:9.4.7.v20170914" level="project" />
    <orderEntry type="library" name="Gradle: org.eclipse.jetty.websocket:websocket-common:9.4.7.v20170914" level="project" />
    <orderEntry type="library" name="Gradle: org.eclipse.jetty:jetty-http:9.4.7.v20170914" level="project" />
    <orderEntry type="library" name="Gradle: org.eclipse.jetty.websocket:websocket-api:9.4.7.v20170914" level="project" />
    <orderEntry type="library" scope="TEST" name="Gradle: junit:junit:4.11" level="project" />
    <orderEntry type="library" scope="TEST" name="Gradle: org.hamcrest:hamcrest-core:1.3" level="project" />
```

If that can help of course.

**Comment by wcrbrm** [comment]
closing this ticket as it related to manual installation which is not recommended
